Links quebrados
detonagirl/POO4Noobs pull request #5
Opened 2022-09-12 17:45 UTC by jeimoal

Todos os links internos, que levavam de um assunto para o outro, estavam quebrados, pois houve alteração no nome dos arquivos.
Corrigi todos eles e agora estão funcionando perfeitamente.

2022-09-12 17:46 UTC, jeimoal commented
Todos os links internos, que levavam de um assunto para o outro, estavam quebrados, pois houve alteração no nome dos arquivos.
Corrigi todos eles e agora estão funcionando perfeitamente.

2022-09-12 17:51 UTC, atomotavio requested changes

2022-09-12 17:51 UTC, atomotavio commented on 1-Paradigmas-de-programacao/2-Historia.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/2-Introducao-POO/1-Introducao-POO.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 2-Introducao-POO/1-Introducao-POO.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/2-Introducao-POO/2-Poo-estruturada.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 2-Introducao-POO/2-Poo-estruturada.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/3-Pilares-POO/1-Pilares-POO.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 3-Pilares-POO/1-Pilares-POO.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/3-Pilares-POO/2-Abstracao.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 3-Pilares-POO/2-Abstracao.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/3-Pilares-POO/3-Encapsulamento.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 3-Pilares-POO/3-Encapsulamento.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/3-Pilares-POO/4-Heranca.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 3-Pilares-POO/4-Heranca.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/3-Pilares-POO/5-Polimorfismo.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 3-Pilares-POO/5-Polimorfismo.md
> +[Próximo capítulo](https://github.com/jeimoal/POO4Noobs/blob/main/4-Tipos-relacionamento/1-Tipos-relacionamento.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-12 17:51 UTC, atomotavio commented on 4-Tipos-relacionamento/1-Tipos-relacionamento.md
> +[Proximo capitulo](https://github.com/jeimoal/POO4Noobs/blob/main/5-Referencias-bibliograficas/1-Referencias-bibliograficas.md)
com o link em https dessa forma ele acaba jogando para o arquivo fork que vc fez do projeto

2022-09-13 16:42 UTC, jeimoal commented
Entendi. Vou atualizar para markdown.

2022-09-13 16:42 UTC, closed without merging